spring:
  application:
    name: reconciliation-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: reconciliation
      auto-offset-reset: earliest
      properties:
        isolation.level: read_committed
